spring.application.name=kinoxp

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/kinoxpdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

pricing.service.base-url=http://localhost:8081
pricing.service.jwt-secret=kinoxp-shared-secret-for-service-jwt-12345
